[package]
name = "switchboard_price_oracle"
version.workspace = true
authors.workspace = true

[cairo]
sierra-replace-ids = true

[dependencies]
openzeppelin.workspace = true
snforge_std.workspace = true
starknet.workspace = true

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
# Enable Sierra codegen.
sierra = true
# Enable CASM codegen.
casm = false

[tool]
fmt.workspace = true
snforge.workspace = true
