snippets:
  - name: "Create a Data Feed"
    description: ""
    filename: "create-feed.ts"
  - name: "Create a Job on IPFS"
    description:
      "A set of jobs must be encoded with the [following
      structure](https://ipfs.io/ipfs/bafybeiaprigfe7hakc4hgqyrjtgsbggrpvzfufpufzvpwtzlznyjb5hjw4/%20USD).
      This example uses [web3.storage](https://web3.storage)."
    filename: "create-job-ipfs.ts"
  - name: ""
    description: ""
    filename: ""
