snippets:
  - name: "Load Switchboard Program"
    description: ""
    filename: "load-program.ts"
  - name: "Transactions"
    description: "Most SDK methods have an optional TransactionOptions parameter to provide overrides."
    filename: "transaction-options.ts"
  - name: "Create a Queue"
    description: ""
    filename: "create-queue.ts"
  - name: "Add an Oracle"
    description: ""
    filename: "add-an-oracle.ts"
  - name: "Create a Job on IPFS"
    description:
      "A set of jobs must be encoded with the [following
      structure](https://ipfs.io/ipfs/bafybeiaprigfe7hakc4hgqyrjtgsbggrpvzfufpufzvpwtzlznyjb5hjw4/%20USD).
      This example uses [web3.storage](https://web3.storage)."
    filename: "create-job-ipfs.ts"
  - name: "Create a Data Feed"
    description: ""
    filename: "create-a-data-feed.ts"
  - name: "Read a Data Feed"
    description: "After the oracles respond, read the feed result"
    filename: "read-data-feed.ts"
  - name: "Watch Data Feed"
    description:
      "Setup a websocket listener to invoke a callback whenever an aggregator is
      updated"
    filename: "watch-data-feed.ts"